language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7.0

before_install:
    - sudo pip install codecov

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit --coverage-text --bootstrap vendor/autoload.php --coverage-clover=coverage.xml

after_success:
    - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then codecov --min-coverage=50; fi
